dist: bionic

language: ruby

sudo: required

git:
  submodules: true

sudo: required

before_install:
  - sudo apt-get update

script:
  - git clone https://github.com/cesko-digital/p-ucime-online.wiki.git wiki
  - cd wiki
  - python3 wiki2gh-pages.py --source . --target .. --dirs images
  - cd ..

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

